version: '3.9'

services:
  db:
    image: mariadb:10.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: burkeexport
      MYSQL_USER: burkeuser
      MYSQL_PASSWORD: burkeexport123
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app  # hot reload
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles

volumes:
  db_data:
