# Generated by Django 5.2.2 on 2025-06-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_es', models.CharField(max_length=100, null=True)),
                ('nombre_en', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='EntradaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('titulo_es', models.CharField(max_length=200, null=True)),
                ('titulo_en', models.CharField(max_length=200, null=True)),
                ('contenido', models.TextField()),
                ('contenido_es', models.TextField(null=True)),
                ('contenido_en', models.TextField(null=True)),
                ('imagen', models.ImageField(upload_to='blog/')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrada de Blog',
                'verbose_name_plural': 'Entradas de Blog',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_es', models.CharField(max_length=200, null=True)),
                ('nombre_en', models.CharField(max_length=200, null=True)),
                ('descripcion', models.TextField()),
                ('descripcion_es', models.TextField(null=True)),
                ('descripcion_en', models.TextField(null=True)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.categoria')),
            ],
        ),
    ]
